version: '3'

services:
  db: 
    image: mysql
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db    

  web:
    image: web
    restart: always
    depends_on:
      - db    

  proxy:
    image: proxy
    ports:
      - 80:80
    depends_on:
      - web
    restart: always