version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080