version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
